version: "3.9"
services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ucet_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:admin@db:5432/ucet_db
      - DATABASE_URL_DOCKER=postgres://postgres:admin@localhost:5432/ucet_db
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=1h
      - REFRESH_SECRET=${REFRESH_SECRET}
      - REFRESH_EXPIRY=7d
      - NODEMAILER_USER=${NODEMAILER_USER}
      - NODEMAILER_PASS=${NODEMAILER_PASS}
      - BASE_URL=http://localhost:5000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=ap-south-1
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

volumes:
  db-data:
